### ISSUE TITLE
Screenity recordings don't work on my linux desktop editors

### ISSUE THREAD

**Issue by quesada** [alyssaxuu/screenity#45] opened 2020-12-29 14:10 UTC
First, congrats on blowing every other recorder out of the water :)
I seem to have a problem with recordings (tried mp4, webm) from screenity. They  don't work on any linux editor shotcut, Davinci, kdenlive and lightworks. Some like shotcut can play them, but dragging them to a track produces a freeze.

Maybe the problem is on my system (drivers?). This is a manjaro install with nvidia 455. Maybe its the variable encoding? I know nothing about video :)

**Comment by alyssaxuu** [comment] 2020-12-29 14:17
Hi, yes, this is an issue caused by a Chrome bug when generating the video file with the MediaRecorder, the duration metadata is set to infinity, which leads to some problems when using certain tools. I believe VLC player works fine, and uploading to Drive & then downloading the resulting file fixes the issue, so there's currently some workarounds even if they might not be the most intuitive.

I have plans to fix this, although so far the only option is for me to spend $$ on a server which I can't really justify due to the extension being free and open source, and it would also mean that people might complain about privacy (since it's all client-side only right now). I'll close this issue as it's the same as #15 & #7 essentially, I just need to figure out how to go about it.

**Closed by alyssaxuu** 2020-12-29 14:17 UTC
