### ISSUE TITLE
Unable to get out of annotation mode.

### ISSUE THREAD

**Issue by ramphub** [alyssaxuu/screenity#97] opened 2021-07-29 20:44 UTC
Great tool! 
Once we get into annotation mode, unable to exit out of it. The only possible way is now to pause the recording and get back to operating the screen.

**Comment by alyssaxuu** [comment] 2022-01-15 09:48
That's strange, I can't reproduce. What steps are you following? In order to disable annotations, after you click for example the pen tool to enable it, you have to click on it again to disable it. Maybe that isn't clear?

**Comment by alyssaxuu** [comment] 2023-12-27 17:11
Should be fixed in the new MV3 version.

**Closed by alyssaxuu** 2023-12-27 17:11 UTC
Labels: question
