### ISSUE TITLE
MP4 format not liked by macOS

### ISSUE THREAD

**Issue by yene** [alyssaxuu/screenity#7] opened 2020-11-21 15:17 UTC
The exported mp4 is not compatible with macOS, it is opus instead of h264 I think.

**Comment by alyssaxuu** [comment] 2020-11-21 15:20
Yeah I am aware of this - the issue is that the FFMPEG.js library does not support the OPUS audio format for Webm videos and thus is unable to properly convert the video to MP4. I'm using a workaround right now which indeed causes some compatibility issues. I'd have to use an API or server to run FFMPEG (which has OPUS support), but the issue is that it's costly, and since I'm not charging anything for the extension it's not something I can really afford :/

**Comment by forresto** [comment] 2020-11-23 07:52
https://github.com/ffmpegwasm/ffmpeg.wasm is an alternative to FFMPEG.js... I haven't looked into wasm in extensions, but it might work?!

**Comment by alyssaxuu** [comment] 2020-11-23 08:39
> https://github.com/ffmpegwasm/ffmpeg.wasm is an alternative to FFMPEG.js... I haven't looked into wasm in extensions, but it might work?!

I feel like I might have tried that out but it was wayyyy too slow - I'll check it out again though nonetheless. I think doing the conversion in the client side is just too hard, I might have to explore options to do it server-side, it just costs $$.

**Comment by megaroeny** [comment] 2020-11-24 01:12
The work around for Mac users for now, just drag the file to your browser tab bar. Works perfectly 😉  But you still can't open it in a desktop client.

**Comment by forresto** [comment] 2020-11-24 07:53
In theory ffmpeg.wasm is 2x slower than native ffmpeg. If you factor in the time/cost of transferring to/from the server, keeping it local is going to win. (Unless you want to compete with the screen capture companies that have cloud sharing features.)

**Comment by alyssaxuu** [comment] 2020-11-24 09:13
> In theory ffmpeg.wasm is 2x slower than native ffmpeg. If you factor in the time/cost of transferring to/from the server, keeping it local is going to win. (Unless you want to compete with the screen capture companies that have cloud sharing features.)

I did try doing it locally and for a ~10 second video it took a good 5 minutes to convert, which was terrible.

**Comment by megaroeny** [comment] 2020-11-24 16:26
Just tried opening the mp4 file in [VLC player](https://www.videolan.org/vlc/download-macosx.html), and it works! So you can use that if you just want to play it on your Mac desktop.

I also just confirmed that the generated mp4 files work when uploading to YouTube too.

**Comment by prashant-shahi** [comment] 2021-02-11 07:46
> > https://github.com/ffmpegwasm/ffmpeg.wasm is an alternative to FFMPEG.js... I haven't looked into wasm in extensions, but it might work?!
> 
> I feel like I might have tried that out but it was wayyyy too slow

@alyssaxuu You are right. I tried it a couple of weeks back. It was painfully slow. :disappointed:

**Comment by jk2K** [comment] 2021-04-10 09:09
there are compatibility issues  with `mp4` export format。 If you want a correct mp4 format, download `webm`, then convert it

you can convert it by yourself with the command `ffmpeg -fflags +genpts -i 1.webm -r 24 1.mp4`

**Comment by dalei2019** [comment] 2022-01-11 05:47
same issue

**Comment by alyssaxuu** [comment] 2023-12-27 17:11
Fixed in the MV3 version.

**Closed by alyssaxuu** 2023-12-27 17:11 UTC
Labels: question
