### ISSUE TITLE
Audio loop every 30sec

### ISSUE THREAD

**Issue by EdouardMD** [alyssaxuu/screenity#205] opened 2024-01-15 15:21 UTC
Screenity software currently has a bug where only the audio portion of the recording continuously loops, specifically the first 30 seconds.

- Windows Media Player can't read it
- VLC can read it 
- I can't convert it to mp4 with ffmpeg

Screenity : V3.1 
chrome : V120.0.6099.217

**Comment by alyssaxuu** [comment] 2024-01-17 11:26
That seems very odd. If you attempt [recovering the recording](https://help.screenity.io/troubleshooting/9Jy5RGjNrBB42hqUdREQ7W/i-can%E2%80%99t-find-my-last-recorded-video-how-can-i-recover-it/rbuLfCAYqemKSJwcvB7vA3) or using the option below to download troubleshooting data, does the video play fine? It might be an issue with transferring the recording data from the service worker into the editor page, since it's sandboxed. In larger videos the data is sent in batches due to the sendMessage file size limit (which also does not support blobs, so must be turned into base64 first), what might be happening is they're received out of order, some chunk is missing, or some batches are repeated causing the issue. I'm currently working on a patch to improve on this system and avoid this error (although I haven't been able to reproduce it in any machine / Chrome version).

The alternative could be an issue with IndexedDB itself that I'm using to store all the video chunks in while recording, if the recovered video also has the same problem. I will need to investigate nonetheless, hopefully have a patch ready in the coming days.

**Comment by EdouardMD** [comment] 2024-01-17 15:04
Hi, here is the output of the troubleshooting section : 
https://files.edouard.ml/share/znP-BsRr
password : alyssax
content : 
- troubleshoot data
- backed up video
- raw data

The backed up video is also damaged.
I will of course be happy to provide you with any additional information if needed.

**Comment by alyssaxuu** [comment] 2024-01-17 21:07
Thank you so much for sharing this. I have looked into the file with ffprobe and there is a jump at the 30 second mark, where the frame goes back to 0 and up again, and once more at the 60 second mark. This is the case even on the raw recording file, so it's not a processing issue.

It's either an issue with the MediaRecorder itself ([similar jump-y behavior has been reported in the past](https://bugzilla.mozilla.org/show_bug.cgi?id=1294753)), or there was simply some sort of repetition / order issue when saving or retrieving the chunks in the IndexedDB somehow. Although the fact it only happens with the audio is really weird.

I've just made some changes to the recording process to try to prevent that, although unless I'm able to reproduce it it's hard to know if it will fix your issue. Probably won't be able to have a release ready in a few days though I'm afraid.

**Comment by myktra** [comment] 2024-01-17 22:33
Hi there! Running in to this exact same issue, at roughly the 30 second mark and again at 60.

macOS 14.1, Chrome 120.

**Comment by MichaelPrecel** [comment] 2024-01-29 01:10
Hey! I'm experiencing an issue with this as well unfortunately OS X 10.15.7 / Chrome 120

**Comment by alyssaxuu** [comment] 2024-01-29 10:40
> Hey! I'm experiencing an issue with this as well unfortunately OS X 10.15.7 / Chrome 120

Is this in the latest 3.1.4 version of Screenity? I still haven't been able to pinpoint the issue, I might need to replace the Localbase library with a different one since I'm afraid it might be the culprit.

**Comment by MichaelPrecel** [comment] 2024-01-29 11:24
Hey @alyssaxuu – yep, it's on version 3.1.4.

**Comment by alyssaxuu** [comment] 2024-02-14 17:21
I'm closing this since I have not had any further reports of this particular issue, but do reopen if it's still the case.

**Closed by alyssaxuu** 2024-02-14 17:21 UTC
Labels: bug

**Comment by MichaelPrecel** [comment] 2024-02-14 21:41
Thanks, I reinstalled and used yesterday without issue!


Cheers,

Michael Precel

Design & Development

Phone 0422 769 123 <+61422769123>

Social @mikepre <https://www.instagram.com/mikepre/>

Website michaelprecel.com <https://www.michaelprecel.com/>

Address 699 Nicholson St, Carlton North 3054
<https://maps.app.goo.gl/QymeKa2VhsNqsAmF6>

Hours 9:30am–5:00pm, Monday–Thursday

Please note, I check my inbox twice a day
in the morning and afternoon. For anything
urgent, please feel free to send me a text.

Working on unceded Wurundjeri and Boonwurrung Land

**Comment by EdouardMD** [comment] 2024-02-15 21:28
Hey @alyssaxuu,
The issue seems to be resolved, thank you !
